language: php

services:
  - mysql

php:
  - 7.2

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --dev --prefer-dist --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE yii2_basic_tests;'
  - php yii_test migrate --interactive=0
  - php yii_test migrate --interactive=0 --migrationPath=vendor/pantera-digital/yii2-seo/migrations

script:
  - vendor/bin/codecept run
